docker_repo_key_url: https://download.docker.com/linux/debian/gpg
docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable"
docker_compose_version: "v2.29.6"
docker_compose_path: /usr/local/bin/docker-compose